### ISSUE TITLE
Create a basic server Docker image

### ISSUE THREAD

**Issue by genaris** [2060-io/credo-ts-indy-vdr-proxy#27]
Currently, this project is deploying both client and server to npm, in order to be consumed by other apps. It will be useful to also create a Dockerfile for the server, that can be deployed to DockerHub and serve as a ready to use, base image.

Resulting image can be published as `io2060/indy-vdr-proxy`. For the moment it is enough to use the tag `dev` .

@gabrielmatau79 you can take current code from our mediator (the one under `src/vdrproxy`) but make it call the internal proxy code instead of using it as an external dependency.

**Comment by bryce-mcmath** [comment]
I'm not sure if this helps but this is the Dockerfile we created for our server that makes use of this package: https://github.com/bcgov/indy-vdr-proxy-server/blob/main/Dockerfile
